openapi: 3.0.0
info:
  title: Trail Management API
  description: Api for managing trails
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Trail:
      type: object
      properties:
        trailID:
          type: integer
        trailName:
          type: string
        trailSummary:
          type: string
        trailDescription:
          type: string
        difficulty:
          type: string
        location:
          type: string
        length:
          type: number
        elevationGain:
          type: number
        routeType:
          type: string
        ownerID:
          type: integer

    SendTrail:
      type: object
      properties:
        trailName:
          type: string
        trailSummary:
          type: string
        trailDescription:
          type: string
        difficulty:
          type: string
        location:
          type: string
        length:
          type: number
        elevationGain:
          type: number
        routeType:
          type: string
        ownerID:
          type: integer

    Feature:
      type: object
      properties:
        featureID:
          type: integer
        trailFeature:
          type: string

    Location:
      type: object
      properties:
        latitude:
          format: float
        longitude:
          format: float
        description:
          type: string
        locationPointID:
          type: integer

paths:
  /users/login:
    post:
      summary: Log in
      operationId: authenticate.login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emailAddress:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Log in result
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                minItems: 2
                maxItems: 2
                example:
                  - "Verified"
                  - "True"
        404:
          description: User does not exist
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  
  /users/logout:
    post:
      summary: Log out
      operationId: authenticate.logout
      tags:
        - Authentication
      responses:
        200:
          description: Logged out
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        400:
          description: Failed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /trails:
    get:
      summary: Get all trails
      operationId: trails.read_all
      tags:
        - Trails
      responses:
        200:
          description: A list of trails
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Trail"
    post:
      summary: Create a trail
      operationId: trails.create
      tags:
        - Trails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendTrail"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"

  /trails/{trailID}:
    get:
      summary: Get a trail
      operationId: trails.read_one
      tags:
        - Trails
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A trail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        404:
          description: Trail not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    put:
      summary: Update a trail
      operationId: trails.update
      tags:
        - Trails
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendTrail"
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        404:
          description: Trail not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    delete:
      summary: Delete a trail
      operationId: trails.delete
      tags:
        - Trails
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Trail not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /features:
    get:
      summary: Get all features
      operationId: features.read_all
      tags:
        - Features
      responses:
        200:
          description: A list of features
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
    
    post:
      summary: Create a feature
      operationId: features.create
      tags:
        - Features
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feature"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: string

  /features/{featureID}:
    get:
      summary: Get a feature
      operationId: features.read_one
      tags:
        - Features
      parameters:
        - name: featureID
          in: path
          required: true
          schema:
              properties:
                trailFeature:
                  type: string
      responses:
        200:
          description: A feature
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
        404:
          description: Feature not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    put:
      summary: Update a feature
      operationId: features.update
      tags:
        - Features
      parameters:
        - name: featureID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Feature"
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                type: string
        404:
          description: Feature not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    delete:
      summary: Delete a feature
      operationId: features.delete
      tags:
        - Features
      parameters:
        - name: featureID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Feature not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /trailFeatures:
    post:
      summary: Add a feature to a trail
      operationId: trailFeatures.create
      tags:
        - Trail Features Link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                trailID:
                  type: integer
                featureID:
                  type: integer
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: string

  /trailFeatures/{trailID}:
    get:
      summary: Get all features of a trail
      operationId: trailFeatures.read_features_for_trail
      tags:
        - Trail Features Link
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A list of features
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Trail not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /trailFeatures/{trailID}/{featureID}:
    delete:
      summary: Remove a feature from a trail
      operationId: trailFeatures.delete
      tags:
        - Trail Features Link
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
        - name: featureID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Trail or feature not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /location:
    get:
      summary: Get a list of all points
      operationId: locations.read_all
      tags:
        - Locations
      responses:
        200:
          description: A list of trails
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        404:
          description: Location not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post: 
      summary: Create a location
      operationId: locations.create
      tags:
        - Locations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: string

  /location/{locationPointID}:
    get:
      summary: Get a location
      operationId: locations.read_one
      tags:
        - Locations
      parameters:
        - name: locationPointID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A location
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        404:
          description: Location not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    put:
      summary: Update a location
      operationId: locations.update
      tags:
        - Locations
      parameters:
        - name: locationPointID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                type: string
        404:
          description: Location not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    delete:
      summary: Delete a location
      operationId: locations.delete
      tags:
        - Locations
      parameters:
        - name: locationPointID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Location not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      
  /trailLocations:
    post:
      summary: Add a location to a trail
      operationId: trailLocations.create
      tags:
        - Trail Locations Link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                trailID:
                  type: integer
                locationPointID:
                  type: integer
                orderNo:
                  type: integer
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: string

  /trailLocations/{trailID}:
    get:
      summary: Get all locations of a trail
      operationId: trailLocations.read_locations_for_trail
      tags:
        - Trail Locations Link
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A list of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
        404:
          description: Trail not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /trailLocations/{trailID}/{locationPointID}:
    delete:
      summary: Remove a location from a trail
      operationId: trailLocations.delete
      tags:
        - Trail Locations Link
      parameters:
        - name: trailID
          in: path
          required: true
          schema:
            type: integer
        - name: locationPointID
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        404:
          description: Trail or location not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

tags:
  - name: Authentication
  - name: Trails
  - name: Features
  - name: Trail Features Link
  - name: Locations